CREATE DATABASE ECOMM_SHOP;
USE ECOMM_SHOP;
CREATE USER 'ECOMM_SHOP'@'localhost' IDENTIFIED BY 'ecommerce';
GRANT ALL PRIVILEGES ON ECOMM_SHOP.* TO 'ECOMM_SHOP'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;

DROP TABLE IF EXISTS ECOMM_SHOP.CATROLES ;
  CREATE TABLE ECOMM_SHOP.CATROLES (
	LANG_TP_CD INT(11)   NOT NULL AUTO_INCREMENT, 
	ID_ROL INT(11)    NOT NULL,
	DESC_ROL VARCHAR(255)   NOT NULL , 
	STATUS_FLAG INT(2)    NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
	LAST_UPDATE_TX_ID INT(11)    , 
	LAST_UPDATE_USER VARCHAR(50)   ,
	PRIMARY KEY (ID_ROL)
  ) ENGINE=INNODB;

  DROP TABLE IF EXISTS ECOMM_SHOP.CATPAGO ;
  CREATE TABLE ECOMM_SHOP.CATPAGO (
    LANG_TP_CD INT(11)    NOT NULL  AUTO_INCREMENT, 
	ID_PAGO INT(11)    NOT NULL,
	COD_PAGO VARCHAR(5)   NOT NULL , 
	DESC_PAGO VARCHAR(255)   NOT NULL , 
	STATUS_FLAG INT(2)    NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
	LAST_UPDATE_TX_ID INT(11)    , 
	LAST_UPDATE_USER VARCHAR(50)  ,
	PRIMARY KEY (ID_PAGO) 
  ) ENGINE=INNODB;

  DROP TABLE IF EXISTS ECOMM_SHOP.CATDESARROLLO ;
  CREATE TABLE ECOMM_SHOP.CATDESARROLLO (
    LANG_TP_CD INT(11)    NOT NULL  AUTO_INCREMENT, 
	ID_DESARROLLO INT(11)    NOT NULL,
	COD_DESARROLLO VARCHAR(10)   NOT NULL ,
	DESC_DESARROLLO VARCHAR(255)   NOT NULL , 
	STATUS_FLAG INT(2)    NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
	LAST_UPDATE_TX_ID INT(11)    , 
	LAST_UPDATE_USER VARCHAR(50) ,
	PRIMARY KEY (ID_DESARROLLO)  
  ) ENGINE=INNODB;

  DROP TABLE IF EXISTS ECOMM_SHOP.CATLENGUAJE ;
  CREATE TABLE ECOMM_SHOP.CATLENGUAJE (
    LANG_TP_CD INT(11)    NOT NULL  AUTO_INCREMENT, 
	ID_LENGUAJE INT(11)    NOT NULL,
	DESC_LENGUAJE VARCHAR(255)   NOT NULL , 
	STATUS_FLAG INT(2)    NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
	LAST_UPDATE_TX_ID INT(11)    , 
	LAST_UPDATE_USER VARCHAR(50) ,
	PRIMARY KEY (ID_LENGUAJE)  
  ) ENGINE=INNODB;

  DROP TABLE IF EXISTS ECOMM_SHOP.CATMONEDA ;
   CREATE TABLE ECOMM_SHOP.CATMONEDA (
    LANG_TP_CD INT(11)    NOT NULL  AUTO_INCREMENT, 
	ID_MONEDA INT(11)    NOT NULL,
	COD_MONEDA VARCHAR(5)   NOT NULL , 
	DESC_MONEDA VARCHAR(255)   NOT NULL , 
	STATUS_FLAG INT(2)    NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
	LAST_UPDATE_TX_ID INT(11)    , 
	LAST_UPDATE_USER VARCHAR(50)   ,
	PRIMARY KEY (ID_MONEDA)
  ) ENGINE=INNODB;

   DROP TABLE IF EXISTS ECOMM_SHOP.CATCATEGORIA ;
  CREATE TABLE ECOMM_SHOP.CATCATEGORIA (
    LANG_TP_CD INT(11)    NOT NULL  AUTO_INCREMENT, 
	ID_CATEGORIA INT(11)    NOT NULL,
	DESC_CATEGORIA VARCHAR(255)   NOT NULL , 
	STATUS_FLAG INT(2)    NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
	LAST_UPDATE_TX_ID INT(11)    , 
	LAST_UPDATE_USER VARCHAR(50)   ,
	PRIMARY KEY (ID_CATEGORIA)
  ) ENGINE=INNODB;

  DROP TABLE IF EXISTS ECOMM_SHOP.CATCALIFICACION ;
  CREATE TABLE ECOMM_SHOP.CATCALIFICACION (
    LANG_TP_CD INT(11)    NOT NULL  AUTO_INCREMENT, 
	ID_CALIFICACION INT(11)    NOT NULL,
	DESC_CALIFICACION VARCHAR(255)   NOT NULL , 
	STATUS_FLAG INT(2)    NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
	LAST_UPDATE_TX_ID INT(11)    , 
	LAST_UPDATE_USER VARCHAR(50)   ,
	PRIMARY KEY (ID_CALIFICACION)
  ) ENGINE=INNODB;

  DROP TABLE IF EXISTS ECOMM_SHOP.CATCUENTA ;
    CREATE TABLE ECOMM_SHOP.CATCUENTA (
    LANG_TP_CD INT(11)    NOT NULL  AUTO_INCREMENT, 
	ID_CUENTA INT(11)    NOT NULL,
	DESC_CUENTA VARCHAR(255)   NOT NULL , 
	STATUS_FLAG INT(2)    NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
	LAST_UPDATE_TX_ID INT(11)    , 
	LAST_UPDATE_USER VARCHAR(50)   ,
	PRIMARY KEY (ID_CUENTA)
  ) ENGINE=INNODB;
  
  DROP TABLE IF EXISTS ECOMM_SHOP.USUARIO_ALIAS ;
  CREATE TABLE ECOMM_SHOP.USUARIO_ALIAS (
	ID_USUARIO INTEGER   NOT NULL,
    USUARIO_TOKEN VARCHAR(255)   NOT NULL ,
	USUARIO_ALIAS VARCHAR(255)   NOT NULL ,
	USUARIO_EMAIL VARCHAR(255)   NOT NULL ,
	USUARIO_PASS VARCHAR(255)   NOT NULL ,
	ID_ROL INTEGER   NOT NULL,
	STATUS_FLAG INTEGER   NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
	LAST_UPDATE_TX_ID INTEGER   , 
	LAST_UPDATE_USER VARCHAR(20) ,
	PRIMARY KEY (ID_USUARIO) 
  ) ENGINE=INNODB;
	alter table ECOMM_SHOP.USUARIO_ALIAS add foreign key(ID_ROL) references ECOMM_SHOP.CATROLES (ID_ROL);

DROP TABLE IF EXISTS ECOMM_SHOP.USUARIO_PERSONA ;
  CREATE TABLE ECOMM_SHOP.USUARIO_PERSONA (
	ID_PERSONA INTEGER   NOT NULL,
    PERSONA_TOKEN VARCHAR(255)   NOT NULL ,
	PERSONA_NOMBRE VARCHAR(255)   NOT NULL ,
	PERSONA_APELLIDOS VARCHAR(255)   NOT NULL ,
	PERSONA_SEXO INTEGER   NOT NULL,
	PERSONA_FECHA_NACIMIENTO DATE,
	PERSONA_EDAD INTEGER   NOT NULL,
	ID_USUARIO INTEGER   NOT NULL,
	STATUS_FLAG INTEGER   NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
	LAST_UPDATE_TX_ID INTEGER   , 
	LAST_UPDATE_USER VARCHAR(20) ,
	PRIMARY KEY (ID_PERSONA) 
  ) ENGINE=INNODB;
	alter table ECOMM_SHOP.USUARIO_PERSONA add foreign key(ID_USUARIO) references ECOMM_SHOP.USUARIO_ALIAS (ID_USUARIO);

DROP TABLE IF EXISTS ECOMM_SHOP.USUARIO_DIRECCION ;
  CREATE TABLE ECOMM_SHOP.USUARIO_DIRECCION (
	ID_DIRECCION INTEGER   NOT NULL,
	DIRECCION_CALLE VARCHAR(255)   NOT NULL ,
	DIRECCION_DELEGACION INTEGER   NOT NULL,
	DIRECCION_ESTADO INTEGER   NOT NULL,
	DIRECCION_CIUDAD INTEGER   NOT NULL,
	DIRECCION_CP INTEGER   NOT NULL,
	ID_PERSONA INTEGER   NOT NULL,
	STATUS_FLAG INTEGER   NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
	LAST_UPDATE_TX_ID INTEGER   , 
	LAST_UPDATE_USER VARCHAR(20)   ,
	PRIMARY KEY (ID_DIRECCION) 
  ) ENGINE=INNODB;
	alter table ECOMM_SHOP.USUARIO_DIRECCION add foreign key(ID_PERSONA) references ECOMM_SHOP.USUARIO_PERSONA (ID_PERSONA);

DROP TABLE IF EXISTS ECOMM_SHOP.METODO_PAGO ;
  CREATE TABLE ECOMM_SHOP.METODO_PAGO (
	ID_METODO INTEGER   NOT NULL,
	METODO_DESC VARCHAR(255)   NOT NULL ,
	METODO_NUMERO INTEGER   NOT NULL,
	METODO_MES INTEGER   NOT NULL,
	METODO_DIA  INTEGER   NOT NULL,
	METODO_NUMSEG INTEGER   NOT NULL,
	ID_PERSONA INTEGER   NOT NULL,
	STATUS_FLAG INTEGER   NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
	LAST_UPDATE_TX_ID INTEGER   , 
	LAST_UPDATE_USER VARCHAR(20) ,
	PRIMARY KEY (ID_METODO) 
  ) ENGINE=INNODB;
	alter table ECOMM_SHOP.METODO_PAGO add foreign key(ID_PERSONA) references ECOMM_SHOP.USUARIO_PERSONA (ID_PERSONA);

DROP TABLE IF EXISTS ECOMM_SHOP.MIS_DESARROLLOS ;
   CREATE TABLE ECOMM_SHOP.MIS_DESARROLLOS (
	ID_MIS_DESARROLLOS INTEGER   NOT NULL,
	ID_DESARROLLO INTEGER   NOT NULL,
	ID_LENGUAJE INTEGER   NOT NULL,
	DESC_MIS_DESARROLLOS VARCHAR(255)   NOT NULL ,
	VERSION_MIS_DESARROLLOS VARCHAR(255)   NOT NULL ,
	COSTO_MIS_DESARROLLOS VARCHAR(255)   NOT NULL ,
	ID_PERSONA INTEGER   NOT NULL,
	ID_PAGO INTEGER   NOT NULL,
	ID_MONEDA INTEGER   NOT NULL,
	STATUS_FLAG INTEGER   NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
	LAST_UPDATE_TX_ID INTEGER   , 
	LAST_UPDATE_USER VARCHAR(20)  	,
	PRIMARY KEY (ID_MIS_DESARROLLOS) 
  ) ENGINE=INNODB;
	alter table ECOMM_SHOP.MIS_DESARROLLOS add foreign key(ID_PERSONA) references ECOMM_SHOP.USUARIO_PERSONA (ID_PERSONA);
	alter table ECOMM_SHOP.MIS_DESARROLLOS add foreign key(ID_DESARROLLO) references ECOMM_SHOP.CATDESARROLLO (ID_DESARROLLO);
	alter table ECOMM_SHOP.MIS_DESARROLLOS add foreign key(ID_LENGUAJE) references ECOMM_SHOP.CATLENGUAJE (ID_LENGUAJE);
	alter table ECOMM_SHOP.MIS_DESARROLLOS add foreign key(ID_PAGO) references ECOMM_SHOP.CATPAGO (ID_PAGO);
	alter table ECOMM_SHOP.MIS_DESARROLLOS add foreign key(ID_MONEDA) references ECOMM_SHOP.CATMONEDA (ID_MONEDA);

DROP TABLE IF EXISTS ECOMM_SHOP.DETALLE_DESARROLLOS ;
  CREATE TABLE ECOMM_SHOP.DETALLE_DESARROLLOS (
	ID_DETALLE_DESARROLLOS INTEGER   NOT NULL,
    ID_MIS_DESARROLLOS INTEGER   NOT NULL,
	OPERACIONES_MIS_DESARROLLOS VARCHAR(255)   NOT NULL ,
	REPORTES_MIS_DESARROLLOS VARCHAR(255)   NOT NULL ,
	IMAGENES VARCHAR(255)   NOT NULL ,
	COMENTARIOS VARCHAR(255)   NOT NULL ,
	STATUS_FLAG INTEGER   NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
	LAST_UPDATE_TX_ID INTEGER   , 
	LAST_UPDATE_USER VARCHAR(20)  	,
	PRIMARY KEY (ID_DETALLE_DESARROLLOS) 
  ) ENGINE=INNODB;
  alter table ECOMM_SHOP.DETALLE_DESARROLLOS add foreign key(ID_MIS_DESARROLLOS) references ECOMM_SHOP.MIS_DESARROLLOS (ID_MIS_DESARROLLOS);

DROP TABLE IF EXISTS ECOMM_SHOP.MIS_CALIFICACIONES ;
  CREATE TABLE ECOMM_SHOP.MIS_CALIFICACIONES (
	ID_MIS_CALIFICACIONES INTEGER   NOT NULL,
	ID_CALIFICACION INTEGER   NOT NULL,
	DESC_CALIFICACION VARCHAR(255)   NOT NULL ,
	ID_MIS_DESARROLLOS INTEGER   NOT NULL,
	ID_PERSONA INTEGER   NOT NULL,
	STATUS_FLAG INTEGER   NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
	LAST_UPDATE_TX_ID INTEGER   , 
	LAST_UPDATE_USER VARCHAR(20)   ,
	PRIMARY KEY (ID_MIS_CALIFICACIONES) 
  ) ENGINE=INNODB;
	alter table ECOMM_SHOP.MIS_CALIFICACIONES add foreign key(ID_PERSONA) references ECOMM_SHOP.USUARIO_PERSONA (ID_PERSONA);
	alter table ECOMM_SHOP.MIS_CALIFICACIONES add foreign key(ID_CALIFICACION) references ECOMM_SHOP.CATCALIFICACION (ID_CALIFICACION);

DROP TABLE IF EXISTS ECOMM_SHOP.MI_CUENTA ;
    CREATE TABLE ECOMM_SHOP.MI_CUENTA (
	ID_MI_CUENTA INTEGER   NOT NULL,
	ID_CUENTA INTEGER   NOT NULL,
	DESC_CUENTA VARCHAR(255)   NOT NULL ,
	ID_PERSONA INTEGER   NOT NULL,
	STATUS_FLAG INTEGER   NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
	LAST_UPDATE_TX_ID INTEGER   , 
	LAST_UPDATE_USER VARCHAR(20)   ,
	PRIMARY KEY (ID_MI_CUENTA) 
  ) ENGINE=INNODB;
    alter table ECOMM_SHOP.MI_CUENTA add foreign key(ID_PERSONA) references ECOMM_SHOP.USUARIO_PERSONA (ID_PERSONA);
    alter table ECOMM_SHOP.MI_CUENTA add foreign key(ID_CUENTA) references ECOMM_SHOP.CATCUENTA (ID_CUENTA);
	
	INSERT INTO ECOMM_SHOP.CATROLES (LANG_TP_CD,ID_ROL,DESC_ROL,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10001,10001,'OPERADOR',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100001,'ADMIN');
INSERT INTO ECOMM_SHOP.CATROLES (LANG_TP_CD,ID_ROL,DESC_ROL,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10002,10002,'ADMINISTRADOR',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100002,'ADMIN');
INSERT INTO ECOMM_SHOP.CATROLES (LANG_TP_CD,ID_ROL,DESC_ROL,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10003,10003,'COMPRADOR\VENDEDOR',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100003,'ADMIN');

INSERT INTO ECOMM_SHOP.CATPAGO (LANG_TP_CD,ID_PAGO,COD_PAGO,DESC_PAGO,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10010,10010,'TDC','TARJETA DE CREDITO',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100010,'ADMIN');
INSERT INTO ECOMM_SHOP.CATPAGO (LANG_TP_CD,ID_PAGO,COD_PAGO,DESC_PAGO,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10011,10011,'TDD','TARJETA DE DEBITO',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100011,'ADMIN');
INSERT INTO ECOMM_SHOP.CATPAGO (LANG_TP_CD,ID_PAGO,COD_PAGO,DESC_PAGO,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10012,10012,'PAYPA','CUENTA PAYPAL',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100012,'ADMIN');

INSERT INTO ECOMM_SHOP.CATMONEDA (LANG_TP_CD,ID_MONEDA,COD_MONEDA,DESC_MONEDA,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10020,10020,'MXN','PESOS MEXICANOS',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100020,'ADMIN');
INSERT INTO ECOMM_SHOP.CATMONEDA (LANG_TP_CD,ID_MONEDA,COD_MONEDA,DESC_MONEDA,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10021,10021,'USD','DOLARES AMERICANOS',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100021,'ADMIN');
INSERT INTO ECOMM_SHOP.CATMONEDA (LANG_TP_CD,ID_MONEDA,COD_MONEDA,DESC_MONEDA,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10022,10022,'EURO','EUROS',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100022,'ADMIN');

INSERT INTO ECOMM_SHOP.CATCUENTA (LANG_TP_CD,ID_CUENTA,DESC_CUENTA,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10030,10030,'BASICA',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100030,'ADMIN');
INSERT INTO ECOMM_SHOP.CATCUENTA (LANG_TP_CD,ID_CUENTA,DESC_CUENTA,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10031,10031,'PREMIUM',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100031,'ADMIN');
INSERT INTO ECOMM_SHOP.CATCUENTA (LANG_TP_CD,ID_CUENTA,DESC_CUENTA,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10032,10032,'PLATINO',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100032,'ADMIN');

INSERT INTO ECOMM_SHOP.CATCALIFICACION (LANG_TP_CD,ID_CALIFICACION,DESC_CALIFICACION,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10040,10040,'MALO',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100040,'ADMIN');
INSERT INTO ECOMM_SHOP.CATCALIFICACION (LANG_TP_CD,ID_CALIFICACION,DESC_CALIFICACION,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10041,10041,'REGULAR',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100041,'ADMIN');
INSERT INTO ECOMM_SHOP.CATCALIFICACION (LANG_TP_CD,ID_CALIFICACION,DESC_CALIFICACION,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10042,10042,'BUENO',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100042,'ADMIN');
INSERT INTO ECOMM_SHOP.CATCALIFICACION (LANG_TP_CD,ID_CALIFICACION,DESC_CALIFICACION,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10043,10043,'EXCELENTE',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100043,'ADMIN');

INSERT INTO ECOMM_SHOP.CATCATEGORIA (LANG_TP_CD,ID_CATEGORIA,DESC_CATEGORIA,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10050,10050,'Relojes y Joyería',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100050,'ADMIN');
INSERT INTO ECOMM_SHOP.CATCATEGORIA (LANG_TP_CD,ID_CATEGORIA,DESC_CATEGORIA,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10051,10051,'Deportes',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100051,'ADMIN');
INSERT INTO ECOMM_SHOP.CATCATEGORIA (LANG_TP_CD,ID_CATEGORIA,DESC_CATEGORIA,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10052,10052,'Cómputo y Electrónica',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100052,'ADMIN');
INSERT INTO ECOMM_SHOP.CATCATEGORIA (LANG_TP_CD,ID_CATEGORIA,DESC_CATEGORIA,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10053,10053,'Celulares',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100053,'ADMIN');
INSERT INTO ECOMM_SHOP.CATCATEGORIA (LANG_TP_CD,ID_CATEGORIA,DESC_CATEGORIA,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10054,10054,'Videojuegos',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100054,'ADMIN');
INSERT INTO ECOMM_SHOP.CATCATEGORIA (LANG_TP_CD,ID_CATEGORIA,DESC_CATEGORIA,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10055,10055,'Libros, Películas y Música',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100055,'ADMIN');
INSERT INTO ECOMM_SHOP.CATCATEGORIA (LANG_TP_CD,ID_CATEGORIA,DESC_CATEGORIA,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10056,10056,'Muebles',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100056,'ADMIN');
INSERT INTO ECOMM_SHOP.CATCATEGORIA (LANG_TP_CD,ID_CATEGORIA,DESC_CATEGORIA,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10057,10057,'Línea Blanca',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100057,'ADMIN');
INSERT INTO ECOMM_SHOP.CATCATEGORIA (LANG_TP_CD,ID_CATEGORIA,DESC_CATEGORIA,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10058,10058,'Automoviles',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100058,'ADMIN');

INSERT INTO ECOMM_SHOP.CATDESARROLLO (LANG_TP_CD,ID_DESARROLLO,COD_DESARROLLO,DESC_DESARROLLO,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10200,10200,'LIB','Librería',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),10200,'ADMIN');
INSERT INTO ECOMM_SHOP.CATDESARROLLO (LANG_TP_CD,ID_DESARROLLO,COD_DESARROLLO,DESC_DESARROLLO,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10201,10201,'APPIOS','Aplicación IOS',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),10201,'ADMIN');
INSERT INTO ECOMM_SHOP.CATDESARROLLO (LANG_TP_CD,ID_DESARROLLO,COD_DESARROLLO,DESC_DESARROLLO,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10202,10202,'APPAND','Aplicacion Android',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),10202,'ADMIN');
INSERT INTO ECOMM_SHOP.CATDESARROLLO (LANG_TP_CD,ID_DESARROLLO,COD_DESARROLLO,DESC_DESARROLLO,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10203,10203,'CRM','Aplicación CRM',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),10203,'ADMIN');
INSERT INTO ECOMM_SHOP.CATDESARROLLO (LANG_TP_CD,ID_DESARROLLO,COD_DESARROLLO,DESC_DESARROLLO,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10204,10204,'WEBDEV','Aplicación Web',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),10204,'ADMIN');
INSERT INTO ECOMM_SHOP.CATDESARROLLO (LANG_TP_CD,ID_DESARROLLO,COD_DESARROLLO,DESC_DESARROLLO,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(10205,10205,'TEMP','Template',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),10205,'ADMIN');

INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100061,100061,'Lenguaje',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100061,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100062,100062,'ADA',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100062,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100063,100063,'BASIC',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100063,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100064,100064,'C',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100064,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100065,100065,'C++',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100065,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100066,100066,'Cobol',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100066,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100067,100067,'Fortran',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100067,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100068,100068,'Java',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100068,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100069,100069,'JSP',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100069,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100070,100070,'MATLAB',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100070,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100071,100071,'Cálculos matemáticos',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100071,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100072,100072,'LISP',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100072,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100073,100073,'Pascal',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100073,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100074,100074,'PHP',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100074,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100075,100075,'Inteligencia artificial',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100075,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100076,100076,'Perl',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100076,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100077,100077,'Ruby',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100077,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100078,100078,'VisualBasic',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100078,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100079,100079,'Objective-C',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100079,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100080,100080,'D',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100080,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100081,100081,'Swift',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100081,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100082,100082,'R',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100082,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100083,100083,'PL/SQL',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100083,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100084,100084,'Groovy',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100084,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100085,100085,'Delphi/Object Pascal',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100085,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100086,100086,'JavaScript',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100086,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100087,100087,'Visual Basic. NET',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100087,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100088,100088,'Python',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100088,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100089,100089,'C#',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100089,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100090,100090,'F#',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100090,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100100,100100,'Haskell',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100100,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100101,100101,'Scala',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100101,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100102,100102,'Clojure',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100102,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100103,100103,'Erlang',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100103,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100104,100104,'Lua',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100104,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100105,100105,'ABAP',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100105,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100106,100106,'ABC',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100106,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100107,100107,'ACTIONSCRIPT',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100107,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100108,100108,'ASP',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100108,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100109,100109,'Clipper',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100109,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100110,100110,'DIV',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100110,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100117,100117,'Ensamblador',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100117,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100111,100111,'Fénix',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100111,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100112,100112,'GML',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100112,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100113,100113,'HTML',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100113,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100114,100114,'Lexico',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100114,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100115,100115,'Logo',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100115,'ADMIN');
INSERT INTO ECOMM_SHOP.CATLENGUAJE (LANG_TP_CD,ID_LENGUAJE,DESC_LENGUAJE,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
VALUES(100116,100116,'Magic',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100116,'ADMIN');


COMMIT;

/*
  INSERT INTO ECOMM_SHOP.CATROLES  (LANG_TP_CD,ID_ROL,DESC_ROL,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
  VALUES(100,10001,'COMPRADOR',1, CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100001,'ADMIN');
    INSERT INTO ECOMM_SHOP.CATROLES  (LANG_TP_CD,ID_ROL,DESC_ROL,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
  VALUES(300,10001,'COMPRADOR',1, CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100001,'ADMIN');

    INSERT INTO ECOMM_SHOP.CATROLES  (LANG_TP_CD,ID_ROL,DESC_ROL,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
  VALUES(100,10002,'VENDEDOR',1, CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100002,'ADMIN');
    INSERT INTO ECOMM_SHOP.CATROLES  (LANG_TP_CD,ID_ROL,DESC_ROL,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
  VALUES(300,10002,'VENDEDOR',1, CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100002,'ADMIN');

    INSERT INTO ECOMM_SHOP.CATROLES  (LANG_TP_CD,ID_ROL,DESC_ROL,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
  VALUES(100,10003,'USUARIO',1, CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100003,'ADMIN');
    INSERT INTO ECOMM_SHOP.CATROLES  (LANG_TP_CD,ID_ROL,DESC_ROL,STATUS_FLAG,EXPIRY_DT,LAST_UPDATE_DT,LAST_UPDATE_TX_ID,LAST_UPDATE_USER)
  VALUES(300,10003,'USUARIO',1, CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),100003,'ADMIN');

COMMIT;
*/
/*
DROP DATABASE ECOMM_SHOP;
DROP USER 'ECOMM_SHOP'@'localhost';

set foreign_key_checks=0;
DROP TABLE ECOMM_SHOP.CATROLES;
DROP TABLE ECOMM_SHOP.CATPAGO;
DROP TABLE ECOMM_SHOP.CATDESARROLLO;
DROP TABLE ECOMM_SHOP.CATLENGUAJE;
DROP TABLE ECOMM_SHOP.CATMONEDA;
DROP TABLE ECOMM_SHOP.CATCATEGORIA;
DROP TABLE ECOMM_SHOP.CATCALIFICACION;
DROP TABLE ECOMM_SHOP.CATCUENTA;

DROP TABLE ECOMM_SHOP.USUARIO_ALIAS;
DROP TABLE ECOMM_SHOP.USUARIO_DIRECCION;
DROP TABLE ECOMM_SHOP.USUARIO_PERSONA;
DROP TABLE ECOMM_SHOP.METODO_PAGO;
DROP TABLE ECOMM_SHOP.MIS_DESARROLLOS;
DROP TABLE ECOMM_SHOP.MIS_CALIFICACIONES;
DROP TABLE ECOMM_SHOP.MI_CUENTA;
DROP TABLE ECOMM_SHOP.DETALLE_DESARROLLOS;

set foreign_key_checks=1;
*/