//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.15 at 11:05:44 PM CDT 
//


package com.allshop.framework.core.ws.catalogoscorporativos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * CrearCatalogoCalificacionInType
 * 			
 * 
 * <p>Java class for CrearCatalogoCalificacionInType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CrearCatalogoCalificacionInType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CatalogoCalificacion" type="{http://www.allshop.com/framework/core/ws/CatalogosCorporativos}CatalogoCalificacion"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CrearCatalogoCalificacionInType", propOrder = {
    "catalogoCalificacion"
})
public class CrearCatalogoCalificacionInType {

    @XmlElement(name = "CatalogoCalificacion", required = true)
    protected CatalogoCalificacion catalogoCalificacion;

    /**
     * Gets the value of the catalogoCalificacion property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogoCalificacion }
     *     
     */
    public CatalogoCalificacion getCatalogoCalificacion() {
        return catalogoCalificacion;
    }

    /**
     * Sets the value of the catalogoCalificacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogoCalificacion }
     *     
     */
    public void setCatalogoCalificacion(CatalogoCalificacion value) {
        this.catalogoCalificacion = value;
    }

}
