//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.15 at 11:05:44 PM CDT 
//


package com.allshop.framework.core.ws.catalogoscorporativos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * CrearCatalogoMonedaInType
 * 
 * <p>Java class for CrearCatalogoMonedaInType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CrearCatalogoMonedaInType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CatalogoMoneda" type="{http://www.allshop.com/framework/core/ws/CatalogosCorporativos}CatalogoMoneda"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CrearCatalogoMonedaInType", propOrder = {
    "catalogoMoneda"
})
public class CrearCatalogoMonedaInType {

    @XmlElement(name = "CatalogoMoneda", required = true)
    protected CatalogoMoneda catalogoMoneda;

    /**
     * Gets the value of the catalogoMoneda property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogoMoneda }
     *     
     */
    public CatalogoMoneda getCatalogoMoneda() {
        return catalogoMoneda;
    }

    /**
     * Sets the value of the catalogoMoneda property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogoMoneda }
     *     
     */
    public void setCatalogoMoneda(CatalogoMoneda value) {
        this.catalogoMoneda = value;
    }

}
