//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.19 at 06:14:45 PM CDT 
//


package com.allshop.framework.core.ws.catalogoscorporativos;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.allshop.framework.core.ws.catalogoscorporativos package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.allshop.framework.core.ws.catalogoscorporativos
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ModificarCatalogoCategoriaIn }
     * 
     */
    public ModificarCatalogoCategoriaIn createModificarCatalogoCategoriaIn() {
        return new ModificarCatalogoCategoriaIn();
    }

    /**
     * Create an instance of {@link ModificarCatalogoRolOut }
     * 
     */
    public ModificarCatalogoRolOut createModificarCatalogoRolOut() {
        return new ModificarCatalogoRolOut();
    }

    /**
     * Create an instance of {@link CrearCatalogoDesarrolloIn }
     * 
     */
    public CrearCatalogoDesarrolloIn createCrearCatalogoDesarrolloIn() {
        return new CrearCatalogoDesarrolloIn();
    }

    /**
     * Create an instance of {@link CrearCatalogoMonedaOut }
     * 
     */
    public CrearCatalogoMonedaOut createCrearCatalogoMonedaOut() {
        return new CrearCatalogoMonedaOut();
    }

    /**
     * Create an instance of {@link CrearCatalogoCuentaIn }
     * 
     */
    public CrearCatalogoCuentaIn createCrearCatalogoCuentaIn() {
        return new CrearCatalogoCuentaIn();
    }

    /**
     * Create an instance of {@link CatalogoCuenta }
     * 
     */
    public CatalogoCuenta createCatalogoCuenta() {
        return new CatalogoCuenta();
    }

    /**
     * Create an instance of {@link ModificarCatalogoDesarrolloOut }
     * 
     */
    public ModificarCatalogoDesarrolloOut createModificarCatalogoDesarrolloOut() {
        return new ModificarCatalogoDesarrolloOut();
    }

    /**
     * Create an instance of {@link CrearCatalogoRolIn }
     * 
     */
    public CrearCatalogoRolIn createCrearCatalogoRolIn() {
        return new CrearCatalogoRolIn();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoCategoriaIn }
     * 
     */
    public ConsultarCatalogoCategoriaIn createConsultarCatalogoCategoriaIn() {
        return new ConsultarCatalogoCategoriaIn();
    }

    /**
     * Create an instance of {@link CatalogoDesarrollo }
     * 
     */
    public CatalogoDesarrollo createCatalogoDesarrollo() {
        return new CatalogoDesarrollo();
    }

    /**
     * Create an instance of {@link CrearCatalogoMonedaIn }
     * 
     */
    public CrearCatalogoMonedaIn createCrearCatalogoMonedaIn() {
        return new CrearCatalogoMonedaIn();
    }

    /**
     * Create an instance of {@link CrearCatalogoCalificacionIn }
     * 
     */
    public CrearCatalogoCalificacionIn createCrearCatalogoCalificacionIn() {
        return new CrearCatalogoCalificacionIn();
    }

    /**
     * Create an instance of {@link CrearCatalogoCategoriaIn }
     * 
     */
    public CrearCatalogoCategoriaIn createCrearCatalogoCategoriaIn() {
        return new CrearCatalogoCategoriaIn();
    }

    /**
     * Create an instance of {@link ModificarCatalogoCalificacionOut }
     * 
     */
    public ModificarCatalogoCalificacionOut createModificarCatalogoCalificacionOut() {
        return new ModificarCatalogoCalificacionOut();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoLenguajeOut }
     * 
     */
    public ConsultarCatalogoLenguajeOut createConsultarCatalogoLenguajeOut() {
        return new ConsultarCatalogoLenguajeOut();
    }

    /**
     * Create an instance of {@link ModificarCatalogoCuentaOut }
     * 
     */
    public ModificarCatalogoCuentaOut createModificarCatalogoCuentaOut() {
        return new ModificarCatalogoCuentaOut();
    }

    /**
     * Create an instance of {@link CrearCatalogoRolOut }
     * 
     */
    public CrearCatalogoRolOut createCrearCatalogoRolOut() {
        return new CrearCatalogoRolOut();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoPagoIn }
     * 
     */
    public ConsultarCatalogoPagoIn createConsultarCatalogoPagoIn() {
        return new ConsultarCatalogoPagoIn();
    }

    /**
     * Create an instance of {@link ModificarCatalogoCuentaIn }
     * 
     */
    public ModificarCatalogoCuentaIn createModificarCatalogoCuentaIn() {
        return new ModificarCatalogoCuentaIn();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoPagoOut }
     * 
     */
    public ConsultarCatalogoPagoOut createConsultarCatalogoPagoOut() {
        return new ConsultarCatalogoPagoOut();
    }

    /**
     * Create an instance of {@link ModificarCatalogoLenguajeOut }
     * 
     */
    public ModificarCatalogoLenguajeOut createModificarCatalogoLenguajeOut() {
        return new ModificarCatalogoLenguajeOut();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoCuentaOut }
     * 
     */
    public ConsultarCatalogoCuentaOut createConsultarCatalogoCuentaOut() {
        return new ConsultarCatalogoCuentaOut();
    }

    /**
     * Create an instance of {@link CrearCatalogoCategoriaOut }
     * 
     */
    public CrearCatalogoCategoriaOut createCrearCatalogoCategoriaOut() {
        return new CrearCatalogoCategoriaOut();
    }

    /**
     * Create an instance of {@link CatalogoMoneda }
     * 
     */
    public CatalogoMoneda createCatalogoMoneda() {
        return new CatalogoMoneda();
    }

    /**
     * Create an instance of {@link ModificarCatalogoPagoIn }
     * 
     */
    public ModificarCatalogoPagoIn createModificarCatalogoPagoIn() {
        return new ModificarCatalogoPagoIn();
    }

    /**
     * Create an instance of {@link CatalogoCalificacion }
     * 
     */
    public CatalogoCalificacion createCatalogoCalificacion() {
        return new CatalogoCalificacion();
    }

    /**
     * Create an instance of {@link CrearCatalogoCalificacionOut }
     * 
     */
    public CrearCatalogoCalificacionOut createCrearCatalogoCalificacionOut() {
        return new CrearCatalogoCalificacionOut();
    }

    /**
     * Create an instance of {@link ModificarCatalogoCategoriaOut }
     * 
     */
    public ModificarCatalogoCategoriaOut createModificarCatalogoCategoriaOut() {
        return new ModificarCatalogoCategoriaOut();
    }

    /**
     * Create an instance of {@link CrearCatalogoLenguajeOut }
     * 
     */
    public CrearCatalogoLenguajeOut createCrearCatalogoLenguajeOut() {
        return new CrearCatalogoLenguajeOut();
    }

    /**
     * Create an instance of {@link CrearCatalogoLenguajeIn }
     * 
     */
    public CrearCatalogoLenguajeIn createCrearCatalogoLenguajeIn() {
        return new CrearCatalogoLenguajeIn();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoCalificacionIn }
     * 
     */
    public ConsultarCatalogoCalificacionIn createConsultarCatalogoCalificacionIn() {
        return new ConsultarCatalogoCalificacionIn();
    }

    /**
     * Create an instance of {@link ModificarCatalogoPagoOut }
     * 
     */
    public ModificarCatalogoPagoOut createModificarCatalogoPagoOut() {
        return new ModificarCatalogoPagoOut();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoLenguajeIn }
     * 
     */
    public ConsultarCatalogoLenguajeIn createConsultarCatalogoLenguajeIn() {
        return new ConsultarCatalogoLenguajeIn();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoMonedaOut }
     * 
     */
    public ConsultarCatalogoMonedaOut createConsultarCatalogoMonedaOut() {
        return new ConsultarCatalogoMonedaOut();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoMonedaIn }
     * 
     */
    public ConsultarCatalogoMonedaIn createConsultarCatalogoMonedaIn() {
        return new ConsultarCatalogoMonedaIn();
    }

    /**
     * Create an instance of {@link CrearCatalogoPagoIn }
     * 
     */
    public CrearCatalogoPagoIn createCrearCatalogoPagoIn() {
        return new CrearCatalogoPagoIn();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoCalificacionOut }
     * 
     */
    public ConsultarCatalogoCalificacionOut createConsultarCatalogoCalificacionOut() {
        return new ConsultarCatalogoCalificacionOut();
    }

    /**
     * Create an instance of {@link CatalogoLenguaje }
     * 
     */
    public CatalogoLenguaje createCatalogoLenguaje() {
        return new CatalogoLenguaje();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoCategoriaOut }
     * 
     */
    public ConsultarCatalogoCategoriaOut createConsultarCatalogoCategoriaOut() {
        return new ConsultarCatalogoCategoriaOut();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoDesarrolloOut }
     * 
     */
    public ConsultarCatalogoDesarrolloOut createConsultarCatalogoDesarrolloOut() {
        return new ConsultarCatalogoDesarrolloOut();
    }

    /**
     * Create an instance of {@link CrearCatalogoPagoOut }
     * 
     */
    public CrearCatalogoPagoOut createCrearCatalogoPagoOut() {
        return new CrearCatalogoPagoOut();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoCuentaIn }
     * 
     */
    public ConsultarCatalogoCuentaIn createConsultarCatalogoCuentaIn() {
        return new ConsultarCatalogoCuentaIn();
    }

    /**
     * Create an instance of {@link ModificarCatalogoDesarrolloIn }
     * 
     */
    public ModificarCatalogoDesarrolloIn createModificarCatalogoDesarrolloIn() {
        return new ModificarCatalogoDesarrolloIn();
    }

    /**
     * Create an instance of {@link ModificarCatalogoMonedaOut }
     * 
     */
    public ModificarCatalogoMonedaOut createModificarCatalogoMonedaOut() {
        return new ModificarCatalogoMonedaOut();
    }

    /**
     * Create an instance of {@link CrearCatalogoDesarrolloOut }
     * 
     */
    public CrearCatalogoDesarrolloOut createCrearCatalogoDesarrolloOut() {
        return new CrearCatalogoDesarrolloOut();
    }

    /**
     * Create an instance of {@link CrearCatalogoCuentaOut }
     * 
     */
    public CrearCatalogoCuentaOut createCrearCatalogoCuentaOut() {
        return new CrearCatalogoCuentaOut();
    }

    /**
     * Create an instance of {@link CatalogoRol }
     * 
     */
    public CatalogoRol createCatalogoRol() {
        return new CatalogoRol();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoRolIn }
     * 
     */
    public ConsultarCatalogoRolIn createConsultarCatalogoRolIn() {
        return new ConsultarCatalogoRolIn();
    }

    /**
     * Create an instance of {@link CatalogoPago }
     * 
     */
    public CatalogoPago createCatalogoPago() {
        return new CatalogoPago();
    }

    /**
     * Create an instance of {@link ModificarCatalogoMonedaIn }
     * 
     */
    public ModificarCatalogoMonedaIn createModificarCatalogoMonedaIn() {
        return new ModificarCatalogoMonedaIn();
    }

    /**
     * Create an instance of {@link ModificarCatalogoRolIn }
     * 
     */
    public ModificarCatalogoRolIn createModificarCatalogoRolIn() {
        return new ModificarCatalogoRolIn();
    }

    /**
     * Create an instance of {@link ModificarCatalogoCalificacionIn }
     * 
     */
    public ModificarCatalogoCalificacionIn createModificarCatalogoCalificacionIn() {
        return new ModificarCatalogoCalificacionIn();
    }

    /**
     * Create an instance of {@link CatalogoCategoria }
     * 
     */
    public CatalogoCategoria createCatalogoCategoria() {
        return new CatalogoCategoria();
    }

    /**
     * Create an instance of {@link ModificarCatalogoLenguajeIn }
     * 
     */
    public ModificarCatalogoLenguajeIn createModificarCatalogoLenguajeIn() {
        return new ModificarCatalogoLenguajeIn();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoRolOut }
     * 
     */
    public ConsultarCatalogoRolOut createConsultarCatalogoRolOut() {
        return new ConsultarCatalogoRolOut();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoDesarrolloIn }
     * 
     */
    public ConsultarCatalogoDesarrolloIn createConsultarCatalogoDesarrolloIn() {
        return new ConsultarCatalogoDesarrolloIn();
    }

}
