//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.15 at 11:05:44 PM CDT 
//


package com.allshop.framework.core.ws.catalogoscorporativos;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.allshop.framework.core.ws.catalogoscorporativos package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ModificarCatalogoCuentaOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ModificarCatalogoCuentaOut");
    private final static QName _ConsultarCatalogoMonedaOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ConsultarCatalogoMonedaOut");
    private final static QName _ConsultarCatalogoCalificacionIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ConsultarCatalogoCalificacionIn");
    private final static QName _ModificarCatalogoRolIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ModificarCatalogoRolIn");
    private final static QName _ConsultarCatalogoMonedaIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ConsultarCatalogoMonedaIn");
    private final static QName _CrearCatalogoMonedaOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "CrearCatalogoMonedaOut");
    private final static QName _ModificarCatalogoCategoriaOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ModificarCatalogoCategoriaOut");
    private final static QName _ConsultarCatalogoCuentaIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ConsultarCatalogoCuentaIn");
    private final static QName _ModificarCatalogoCalificacionOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ModificarCatalogoCalificacionOut");
    private final static QName _ModificarCatalogoRolOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ModificarCatalogoRolOut");
    private final static QName _CrearCatalogoCuentaIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "CrearCatalogoCuentaIn");
    private final static QName _CrearCatalogoCalificacionOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "CrearCatalogoCalificacionOut");
    private final static QName _ModificarCatalogoDesarrolloOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ModificarCatalogoDesarrolloOut");
    private final static QName _ModificarCatalogoPagoIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ModificarCatalogoPagoIn");
    private final static QName _ModificarCatalogoPagoOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ModificarCatalogoPagoOut");
    private final static QName _CrearCatalogoPagoIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "CrearCatalogoPagoIn");
    private final static QName _CrearCatalogoCalificacionIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "CrearCatalogoCalificacionIn");
    private final static QName _ModificarCatalogoCalificacionIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ModificarCatalogoCalificacionIn");
    private final static QName _ConsultarCatalogoCalificacionOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ConsultarCatalogoCalificacionOut");
    private final static QName _ConsultarCatalogoCategoriaIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ConsultarCatalogoCategoriaIn");
    private final static QName _CrearCatalogoMonedaIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "CrearCatalogoMonedaIn");
    private final static QName _ModificarCatalogoLenguajeOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ModificarCatalogoLenguajeOut");
    private final static QName _ConsultarCatalogoRolIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ConsultarCatalogoRolIn");
    private final static QName _ModificarCatalogoLenguajeIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ModificarCatalogoLenguajeIn");
    private final static QName _ModificarCatalogoMonedaIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ModificarCatalogoMonedaIn");
    private final static QName _ConsultarCatalogoCuentaOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ConsultarCatalogoCuentaOut");
    private final static QName _CrearCatalogoCategoriaOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "CrearCatalogoCategoriaOut");
    private final static QName _ConsultarCatalogoLenguajeIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ConsultarCatalogoLenguajeIn");
    private final static QName _CrearCatalogoLenguajeOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "CrearCatalogoLenguajeOut");
    private final static QName _ConsultarCatalogoRolOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ConsultarCatalogoRolOut");
    private final static QName _CrearCatalogoCategoriaIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "CrearCatalogoCategoriaIn");
    private final static QName _ModificarCatalogoCuentaIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ModificarCatalogoCuentaIn");
    private final static QName _CrearCatalogoPagoOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "CrearCatalogoPagoOut");
    private final static QName _ConsultarCatalogoDesarrolloIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ConsultarCatalogoDesarrolloIn");
    private final static QName _ConsultarCatalogoPagoIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ConsultarCatalogoPagoIn");
    private final static QName _ConsultarCatalogoLenguajeOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ConsultarCatalogoLenguajeOut");
    private final static QName _ModificarCatalogoDesarrolloIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ModificarCatalogoDesarrolloIn");
    private final static QName _CrearCatalogoCuentaOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "CrearCatalogoCuentaOut");
    private final static QName _CrearCatalogoDesarrolloIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "CrearCatalogoDesarrolloIn");
    private final static QName _CrearCatalogoLenguajeIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "CrearCatalogoLenguajeIn");
    private final static QName _CrearCatalogoDesarrolloOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "CrearCatalogoDesarrolloOut");
    private final static QName _ConsultarCatalogoCategoriaOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ConsultarCatalogoCategoriaOut");
    private final static QName _ConsultarCatalogoDesarrolloOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ConsultarCatalogoDesarrolloOut");
    private final static QName _ConsultarCatalogoPagoOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ConsultarCatalogoPagoOut");
    private final static QName _ModificarCatalogoCategoriaIn_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ModificarCatalogoCategoriaIn");
    private final static QName _ModificarCatalogoMonedaOut_QNAME = new QName("http://www.allshop.com/framework/core/ws/CatalogosCorporativos", "ModificarCatalogoMonedaOut");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.allshop.framework.core.ws.catalogoscorporativos
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CrearCatalogoCuentaOutType }
     * 
     */
    public CrearCatalogoCuentaOutType createCrearCatalogoCuentaOutType() {
        return new CrearCatalogoCuentaOutType();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoRolOutType }
     * 
     */
    public ConsultarCatalogoRolOutType createConsultarCatalogoRolOutType() {
        return new ConsultarCatalogoRolOutType();
    }

    /**
     * Create an instance of {@link ModificarCatalogoLenguajeOutType }
     * 
     */
    public ModificarCatalogoLenguajeOutType createModificarCatalogoLenguajeOutType() {
        return new ModificarCatalogoLenguajeOutType();
    }

    /**
     * Create an instance of {@link ModificarCatalogoCalificacionInType }
     * 
     */
    public ModificarCatalogoCalificacionInType createModificarCatalogoCalificacionInType() {
        return new ModificarCatalogoCalificacionInType();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoCalificacionOutType }
     * 
     */
    public ConsultarCatalogoCalificacionOutType createConsultarCatalogoCalificacionOutType() {
        return new ConsultarCatalogoCalificacionOutType();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoPagoOutType }
     * 
     */
    public ConsultarCatalogoPagoOutType createConsultarCatalogoPagoOutType() {
        return new ConsultarCatalogoPagoOutType();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoCuentaOutType }
     * 
     */
    public ConsultarCatalogoCuentaOutType createConsultarCatalogoCuentaOutType() {
        return new ConsultarCatalogoCuentaOutType();
    }

    /**
     * Create an instance of {@link CatalogoCategoria }
     * 
     */
    public CatalogoCategoria createCatalogoCategoria() {
        return new CatalogoCategoria();
    }

    /**
     * Create an instance of {@link CrearCatalogoDesarrolloInType }
     * 
     */
    public CrearCatalogoDesarrolloInType createCrearCatalogoDesarrolloInType() {
        return new CrearCatalogoDesarrolloInType();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoMonedaOutType }
     * 
     */
    public ConsultarCatalogoMonedaOutType createConsultarCatalogoMonedaOutType() {
        return new ConsultarCatalogoMonedaOutType();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoPagoInType }
     * 
     */
    public ConsultarCatalogoPagoInType createConsultarCatalogoPagoInType() {
        return new ConsultarCatalogoPagoInType();
    }

    /**
     * Create an instance of {@link CatalogoLenguaje }
     * 
     */
    public CatalogoLenguaje createCatalogoLenguaje() {
        return new CatalogoLenguaje();
    }

    /**
     * Create an instance of {@link CrearCatalogoCategoriaInType }
     * 
     */
    public CrearCatalogoCategoriaInType createCrearCatalogoCategoriaInType() {
        return new CrearCatalogoCategoriaInType();
    }

    /**
     * Create an instance of {@link CatalogoDesarrollo }
     * 
     */
    public CatalogoDesarrollo createCatalogoDesarrollo() {
        return new CatalogoDesarrollo();
    }

    /**
     * Create an instance of {@link CrearCatalogoDesarrolloOutType }
     * 
     */
    public CrearCatalogoDesarrolloOutType createCrearCatalogoDesarrolloOutType() {
        return new CrearCatalogoDesarrolloOutType();
    }

    /**
     * Create an instance of {@link CrearCatalogoCalificacionOutType }
     * 
     */
    public CrearCatalogoCalificacionOutType createCrearCatalogoCalificacionOutType() {
        return new CrearCatalogoCalificacionOutType();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoCategoriaInType }
     * 
     */
    public ConsultarCatalogoCategoriaInType createConsultarCatalogoCategoriaInType() {
        return new ConsultarCatalogoCategoriaInType();
    }

    /**
     * Create an instance of {@link CatalogoPago }
     * 
     */
    public CatalogoPago createCatalogoPago() {
        return new CatalogoPago();
    }

    /**
     * Create an instance of {@link CrearCatalogoLenguajeInType }
     * 
     */
    public CrearCatalogoLenguajeInType createCrearCatalogoLenguajeInType() {
        return new CrearCatalogoLenguajeInType();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoCalificacionInType }
     * 
     */
    public ConsultarCatalogoCalificacionInType createConsultarCatalogoCalificacionInType() {
        return new ConsultarCatalogoCalificacionInType();
    }

    /**
     * Create an instance of {@link CrearCatalogoRolIn }
     * 
     */
    public CrearCatalogoRolIn createCrearCatalogoRolIn() {
        return new CrearCatalogoRolIn();
    }

    /**
     * Create an instance of {@link CatalogoMoneda }
     * 
     */
    public CatalogoMoneda createCatalogoMoneda() {
        return new CatalogoMoneda();
    }

    /**
     * Create an instance of {@link ModificarCatalogoRolInType }
     * 
     */
    public ModificarCatalogoRolInType createModificarCatalogoRolInType() {
        return new ModificarCatalogoRolInType();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoDesarrolloInType }
     * 
     */
    public ConsultarCatalogoDesarrolloInType createConsultarCatalogoDesarrolloInType() {
        return new ConsultarCatalogoDesarrolloInType();
    }

    /**
     * Create an instance of {@link ModificarCatalogoMonedaOutType }
     * 
     */
    public ModificarCatalogoMonedaOutType createModificarCatalogoMonedaOutType() {
        return new ModificarCatalogoMonedaOutType();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoCategoriaOutType }
     * 
     */
    public ConsultarCatalogoCategoriaOutType createConsultarCatalogoCategoriaOutType() {
        return new ConsultarCatalogoCategoriaOutType();
    }

    /**
     * Create an instance of {@link CatalogoCalificacion }
     * 
     */
    public CatalogoCalificacion createCatalogoCalificacion() {
        return new CatalogoCalificacion();
    }

    /**
     * Create an instance of {@link CrearCatalogoCuentaInType }
     * 
     */
    public CrearCatalogoCuentaInType createCrearCatalogoCuentaInType() {
        return new CrearCatalogoCuentaInType();
    }

    /**
     * Create an instance of {@link ModificarCatalogoMonedaInType }
     * 
     */
    public ModificarCatalogoMonedaInType createModificarCatalogoMonedaInType() {
        return new ModificarCatalogoMonedaInType();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoRolInType }
     * 
     */
    public ConsultarCatalogoRolInType createConsultarCatalogoRolInType() {
        return new ConsultarCatalogoRolInType();
    }

    /**
     * Create an instance of {@link CrearCatalogoRolOut }
     * 
     */
    public CrearCatalogoRolOut createCrearCatalogoRolOut() {
        return new CrearCatalogoRolOut();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoMonedaInType }
     * 
     */
    public ConsultarCatalogoMonedaInType createConsultarCatalogoMonedaInType() {
        return new ConsultarCatalogoMonedaInType();
    }

    /**
     * Create an instance of {@link ModificarCatalogoCuentaOutType }
     * 
     */
    public ModificarCatalogoCuentaOutType createModificarCatalogoCuentaOutType() {
        return new ModificarCatalogoCuentaOutType();
    }

    /**
     * Create an instance of {@link CrearCatalogoMonedaOutType }
     * 
     */
    public CrearCatalogoMonedaOutType createCrearCatalogoMonedaOutType() {
        return new CrearCatalogoMonedaOutType();
    }

    /**
     * Create an instance of {@link ModificarCatalogoCalificacionOutType }
     * 
     */
    public ModificarCatalogoCalificacionOutType createModificarCatalogoCalificacionOutType() {
        return new ModificarCatalogoCalificacionOutType();
    }

    /**
     * Create an instance of {@link CrearCatalogoPagoOutType }
     * 
     */
    public CrearCatalogoPagoOutType createCrearCatalogoPagoOutType() {
        return new CrearCatalogoPagoOutType();
    }

    /**
     * Create an instance of {@link CrearCatalogoLenguajeOutType }
     * 
     */
    public CrearCatalogoLenguajeOutType createCrearCatalogoLenguajeOutType() {
        return new CrearCatalogoLenguajeOutType();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoLenguajeOutType }
     * 
     */
    public ConsultarCatalogoLenguajeOutType createConsultarCatalogoLenguajeOutType() {
        return new ConsultarCatalogoLenguajeOutType();
    }

    /**
     * Create an instance of {@link CrearCatalogoCalificacionInType }
     * 
     */
    public CrearCatalogoCalificacionInType createCrearCatalogoCalificacionInType() {
        return new CrearCatalogoCalificacionInType();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoDesarrolloOutType }
     * 
     */
    public ConsultarCatalogoDesarrolloOutType createConsultarCatalogoDesarrolloOutType() {
        return new ConsultarCatalogoDesarrolloOutType();
    }

    /**
     * Create an instance of {@link ModificarCatalogoDesarrolloInType }
     * 
     */
    public ModificarCatalogoDesarrolloInType createModificarCatalogoDesarrolloInType() {
        return new ModificarCatalogoDesarrolloInType();
    }

    /**
     * Create an instance of {@link CrearCatalogoPagoInType }
     * 
     */
    public CrearCatalogoPagoInType createCrearCatalogoPagoInType() {
        return new CrearCatalogoPagoInType();
    }

    /**
     * Create an instance of {@link CatalogoCuenta }
     * 
     */
    public CatalogoCuenta createCatalogoCuenta() {
        return new CatalogoCuenta();
    }

    /**
     * Create an instance of {@link ModificarCatalogoLenguajeInType }
     * 
     */
    public ModificarCatalogoLenguajeInType createModificarCatalogoLenguajeInType() {
        return new ModificarCatalogoLenguajeInType();
    }

    /**
     * Create an instance of {@link CrearCatalogoMonedaInType }
     * 
     */
    public CrearCatalogoMonedaInType createCrearCatalogoMonedaInType() {
        return new CrearCatalogoMonedaInType();
    }

    /**
     * Create an instance of {@link ModificarCatalogoPagoOutType }
     * 
     */
    public ModificarCatalogoPagoOutType createModificarCatalogoPagoOutType() {
        return new ModificarCatalogoPagoOutType();
    }

    /**
     * Create an instance of {@link ModificarCatalogoRolOutType }
     * 
     */
    public ModificarCatalogoRolOutType createModificarCatalogoRolOutType() {
        return new ModificarCatalogoRolOutType();
    }

    /**
     * Create an instance of {@link ModificarCatalogoCategoriaInType }
     * 
     */
    public ModificarCatalogoCategoriaInType createModificarCatalogoCategoriaInType() {
        return new ModificarCatalogoCategoriaInType();
    }

    /**
     * Create an instance of {@link ModificarCatalogoPagoInType }
     * 
     */
    public ModificarCatalogoPagoInType createModificarCatalogoPagoInType() {
        return new ModificarCatalogoPagoInType();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoCuentaInType }
     * 
     */
    public ConsultarCatalogoCuentaInType createConsultarCatalogoCuentaInType() {
        return new ConsultarCatalogoCuentaInType();
    }

    /**
     * Create an instance of {@link CrearCatalogoCategoriaOutType }
     * 
     */
    public CrearCatalogoCategoriaOutType createCrearCatalogoCategoriaOutType() {
        return new CrearCatalogoCategoriaOutType();
    }

    /**
     * Create an instance of {@link ModificarCatalogoCategoriaOutType }
     * 
     */
    public ModificarCatalogoCategoriaOutType createModificarCatalogoCategoriaOutType() {
        return new ModificarCatalogoCategoriaOutType();
    }

    /**
     * Create an instance of {@link ConsultarCatalogoLenguajeInType }
     * 
     */
    public ConsultarCatalogoLenguajeInType createConsultarCatalogoLenguajeInType() {
        return new ConsultarCatalogoLenguajeInType();
    }

    /**
     * Create an instance of {@link ModificarCatalogoDesarrolloOutType }
     * 
     */
    public ModificarCatalogoDesarrolloOutType createModificarCatalogoDesarrolloOutType() {
        return new ModificarCatalogoDesarrolloOutType();
    }

    /**
     * Create an instance of {@link CatalogoRol }
     * 
     */
    public CatalogoRol createCatalogoRol() {
        return new CatalogoRol();
    }

    /**
     * Create an instance of {@link ModificarCatalogoCuentaInType }
     * 
     */
    public ModificarCatalogoCuentaInType createModificarCatalogoCuentaInType() {
        return new ModificarCatalogoCuentaInType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModificarCatalogoCuentaOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ModificarCatalogoCuentaOut")
    public JAXBElement<ModificarCatalogoCuentaOutType> createModificarCatalogoCuentaOut(ModificarCatalogoCuentaOutType value) {
        return new JAXBElement<ModificarCatalogoCuentaOutType>(_ModificarCatalogoCuentaOut_QNAME, ModificarCatalogoCuentaOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCatalogoMonedaOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ConsultarCatalogoMonedaOut")
    public JAXBElement<ConsultarCatalogoMonedaOutType> createConsultarCatalogoMonedaOut(ConsultarCatalogoMonedaOutType value) {
        return new JAXBElement<ConsultarCatalogoMonedaOutType>(_ConsultarCatalogoMonedaOut_QNAME, ConsultarCatalogoMonedaOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCatalogoCalificacionInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ConsultarCatalogoCalificacionIn")
    public JAXBElement<ConsultarCatalogoCalificacionInType> createConsultarCatalogoCalificacionIn(ConsultarCatalogoCalificacionInType value) {
        return new JAXBElement<ConsultarCatalogoCalificacionInType>(_ConsultarCatalogoCalificacionIn_QNAME, ConsultarCatalogoCalificacionInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModificarCatalogoRolInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ModificarCatalogoRolIn")
    public JAXBElement<ModificarCatalogoRolInType> createModificarCatalogoRolIn(ModificarCatalogoRolInType value) {
        return new JAXBElement<ModificarCatalogoRolInType>(_ModificarCatalogoRolIn_QNAME, ModificarCatalogoRolInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCatalogoMonedaInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ConsultarCatalogoMonedaIn")
    public JAXBElement<ConsultarCatalogoMonedaInType> createConsultarCatalogoMonedaIn(ConsultarCatalogoMonedaInType value) {
        return new JAXBElement<ConsultarCatalogoMonedaInType>(_ConsultarCatalogoMonedaIn_QNAME, ConsultarCatalogoMonedaInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrearCatalogoMonedaOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "CrearCatalogoMonedaOut")
    public JAXBElement<CrearCatalogoMonedaOutType> createCrearCatalogoMonedaOut(CrearCatalogoMonedaOutType value) {
        return new JAXBElement<CrearCatalogoMonedaOutType>(_CrearCatalogoMonedaOut_QNAME, CrearCatalogoMonedaOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModificarCatalogoCategoriaOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ModificarCatalogoCategoriaOut")
    public JAXBElement<ModificarCatalogoCategoriaOutType> createModificarCatalogoCategoriaOut(ModificarCatalogoCategoriaOutType value) {
        return new JAXBElement<ModificarCatalogoCategoriaOutType>(_ModificarCatalogoCategoriaOut_QNAME, ModificarCatalogoCategoriaOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCatalogoCuentaInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ConsultarCatalogoCuentaIn")
    public JAXBElement<ConsultarCatalogoCuentaInType> createConsultarCatalogoCuentaIn(ConsultarCatalogoCuentaInType value) {
        return new JAXBElement<ConsultarCatalogoCuentaInType>(_ConsultarCatalogoCuentaIn_QNAME, ConsultarCatalogoCuentaInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModificarCatalogoCalificacionOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ModificarCatalogoCalificacionOut")
    public JAXBElement<ModificarCatalogoCalificacionOutType> createModificarCatalogoCalificacionOut(ModificarCatalogoCalificacionOutType value) {
        return new JAXBElement<ModificarCatalogoCalificacionOutType>(_ModificarCatalogoCalificacionOut_QNAME, ModificarCatalogoCalificacionOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModificarCatalogoRolOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ModificarCatalogoRolOut")
    public JAXBElement<ModificarCatalogoRolOutType> createModificarCatalogoRolOut(ModificarCatalogoRolOutType value) {
        return new JAXBElement<ModificarCatalogoRolOutType>(_ModificarCatalogoRolOut_QNAME, ModificarCatalogoRolOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrearCatalogoCuentaInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "CrearCatalogoCuentaIn")
    public JAXBElement<CrearCatalogoCuentaInType> createCrearCatalogoCuentaIn(CrearCatalogoCuentaInType value) {
        return new JAXBElement<CrearCatalogoCuentaInType>(_CrearCatalogoCuentaIn_QNAME, CrearCatalogoCuentaInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrearCatalogoCalificacionOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "CrearCatalogoCalificacionOut")
    public JAXBElement<CrearCatalogoCalificacionOutType> createCrearCatalogoCalificacionOut(CrearCatalogoCalificacionOutType value) {
        return new JAXBElement<CrearCatalogoCalificacionOutType>(_CrearCatalogoCalificacionOut_QNAME, CrearCatalogoCalificacionOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModificarCatalogoDesarrolloOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ModificarCatalogoDesarrolloOut")
    public JAXBElement<ModificarCatalogoDesarrolloOutType> createModificarCatalogoDesarrolloOut(ModificarCatalogoDesarrolloOutType value) {
        return new JAXBElement<ModificarCatalogoDesarrolloOutType>(_ModificarCatalogoDesarrolloOut_QNAME, ModificarCatalogoDesarrolloOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModificarCatalogoPagoInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ModificarCatalogoPagoIn")
    public JAXBElement<ModificarCatalogoPagoInType> createModificarCatalogoPagoIn(ModificarCatalogoPagoInType value) {
        return new JAXBElement<ModificarCatalogoPagoInType>(_ModificarCatalogoPagoIn_QNAME, ModificarCatalogoPagoInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModificarCatalogoPagoOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ModificarCatalogoPagoOut")
    public JAXBElement<ModificarCatalogoPagoOutType> createModificarCatalogoPagoOut(ModificarCatalogoPagoOutType value) {
        return new JAXBElement<ModificarCatalogoPagoOutType>(_ModificarCatalogoPagoOut_QNAME, ModificarCatalogoPagoOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrearCatalogoPagoInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "CrearCatalogoPagoIn")
    public JAXBElement<CrearCatalogoPagoInType> createCrearCatalogoPagoIn(CrearCatalogoPagoInType value) {
        return new JAXBElement<CrearCatalogoPagoInType>(_CrearCatalogoPagoIn_QNAME, CrearCatalogoPagoInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrearCatalogoCalificacionInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "CrearCatalogoCalificacionIn")
    public JAXBElement<CrearCatalogoCalificacionInType> createCrearCatalogoCalificacionIn(CrearCatalogoCalificacionInType value) {
        return new JAXBElement<CrearCatalogoCalificacionInType>(_CrearCatalogoCalificacionIn_QNAME, CrearCatalogoCalificacionInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModificarCatalogoCalificacionInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ModificarCatalogoCalificacionIn")
    public JAXBElement<ModificarCatalogoCalificacionInType> createModificarCatalogoCalificacionIn(ModificarCatalogoCalificacionInType value) {
        return new JAXBElement<ModificarCatalogoCalificacionInType>(_ModificarCatalogoCalificacionIn_QNAME, ModificarCatalogoCalificacionInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCatalogoCalificacionOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ConsultarCatalogoCalificacionOut")
    public JAXBElement<ConsultarCatalogoCalificacionOutType> createConsultarCatalogoCalificacionOut(ConsultarCatalogoCalificacionOutType value) {
        return new JAXBElement<ConsultarCatalogoCalificacionOutType>(_ConsultarCatalogoCalificacionOut_QNAME, ConsultarCatalogoCalificacionOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCatalogoCategoriaInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ConsultarCatalogoCategoriaIn")
    public JAXBElement<ConsultarCatalogoCategoriaInType> createConsultarCatalogoCategoriaIn(ConsultarCatalogoCategoriaInType value) {
        return new JAXBElement<ConsultarCatalogoCategoriaInType>(_ConsultarCatalogoCategoriaIn_QNAME, ConsultarCatalogoCategoriaInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrearCatalogoMonedaInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "CrearCatalogoMonedaIn")
    public JAXBElement<CrearCatalogoMonedaInType> createCrearCatalogoMonedaIn(CrearCatalogoMonedaInType value) {
        return new JAXBElement<CrearCatalogoMonedaInType>(_CrearCatalogoMonedaIn_QNAME, CrearCatalogoMonedaInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModificarCatalogoLenguajeOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ModificarCatalogoLenguajeOut")
    public JAXBElement<ModificarCatalogoLenguajeOutType> createModificarCatalogoLenguajeOut(ModificarCatalogoLenguajeOutType value) {
        return new JAXBElement<ModificarCatalogoLenguajeOutType>(_ModificarCatalogoLenguajeOut_QNAME, ModificarCatalogoLenguajeOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCatalogoRolInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ConsultarCatalogoRolIn")
    public JAXBElement<ConsultarCatalogoRolInType> createConsultarCatalogoRolIn(ConsultarCatalogoRolInType value) {
        return new JAXBElement<ConsultarCatalogoRolInType>(_ConsultarCatalogoRolIn_QNAME, ConsultarCatalogoRolInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModificarCatalogoLenguajeInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ModificarCatalogoLenguajeIn")
    public JAXBElement<ModificarCatalogoLenguajeInType> createModificarCatalogoLenguajeIn(ModificarCatalogoLenguajeInType value) {
        return new JAXBElement<ModificarCatalogoLenguajeInType>(_ModificarCatalogoLenguajeIn_QNAME, ModificarCatalogoLenguajeInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModificarCatalogoMonedaInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ModificarCatalogoMonedaIn")
    public JAXBElement<ModificarCatalogoMonedaInType> createModificarCatalogoMonedaIn(ModificarCatalogoMonedaInType value) {
        return new JAXBElement<ModificarCatalogoMonedaInType>(_ModificarCatalogoMonedaIn_QNAME, ModificarCatalogoMonedaInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCatalogoCuentaOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ConsultarCatalogoCuentaOut")
    public JAXBElement<ConsultarCatalogoCuentaOutType> createConsultarCatalogoCuentaOut(ConsultarCatalogoCuentaOutType value) {
        return new JAXBElement<ConsultarCatalogoCuentaOutType>(_ConsultarCatalogoCuentaOut_QNAME, ConsultarCatalogoCuentaOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrearCatalogoCategoriaOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "CrearCatalogoCategoriaOut")
    public JAXBElement<CrearCatalogoCategoriaOutType> createCrearCatalogoCategoriaOut(CrearCatalogoCategoriaOutType value) {
        return new JAXBElement<CrearCatalogoCategoriaOutType>(_CrearCatalogoCategoriaOut_QNAME, CrearCatalogoCategoriaOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCatalogoLenguajeInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ConsultarCatalogoLenguajeIn")
    public JAXBElement<ConsultarCatalogoLenguajeInType> createConsultarCatalogoLenguajeIn(ConsultarCatalogoLenguajeInType value) {
        return new JAXBElement<ConsultarCatalogoLenguajeInType>(_ConsultarCatalogoLenguajeIn_QNAME, ConsultarCatalogoLenguajeInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrearCatalogoLenguajeOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "CrearCatalogoLenguajeOut")
    public JAXBElement<CrearCatalogoLenguajeOutType> createCrearCatalogoLenguajeOut(CrearCatalogoLenguajeOutType value) {
        return new JAXBElement<CrearCatalogoLenguajeOutType>(_CrearCatalogoLenguajeOut_QNAME, CrearCatalogoLenguajeOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCatalogoRolOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ConsultarCatalogoRolOut")
    public JAXBElement<ConsultarCatalogoRolOutType> createConsultarCatalogoRolOut(ConsultarCatalogoRolOutType value) {
        return new JAXBElement<ConsultarCatalogoRolOutType>(_ConsultarCatalogoRolOut_QNAME, ConsultarCatalogoRolOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrearCatalogoCategoriaInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "CrearCatalogoCategoriaIn")
    public JAXBElement<CrearCatalogoCategoriaInType> createCrearCatalogoCategoriaIn(CrearCatalogoCategoriaInType value) {
        return new JAXBElement<CrearCatalogoCategoriaInType>(_CrearCatalogoCategoriaIn_QNAME, CrearCatalogoCategoriaInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModificarCatalogoCuentaInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ModificarCatalogoCuentaIn")
    public JAXBElement<ModificarCatalogoCuentaInType> createModificarCatalogoCuentaIn(ModificarCatalogoCuentaInType value) {
        return new JAXBElement<ModificarCatalogoCuentaInType>(_ModificarCatalogoCuentaIn_QNAME, ModificarCatalogoCuentaInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrearCatalogoPagoOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "CrearCatalogoPagoOut")
    public JAXBElement<CrearCatalogoPagoOutType> createCrearCatalogoPagoOut(CrearCatalogoPagoOutType value) {
        return new JAXBElement<CrearCatalogoPagoOutType>(_CrearCatalogoPagoOut_QNAME, CrearCatalogoPagoOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCatalogoDesarrolloInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ConsultarCatalogoDesarrolloIn")
    public JAXBElement<ConsultarCatalogoDesarrolloInType> createConsultarCatalogoDesarrolloIn(ConsultarCatalogoDesarrolloInType value) {
        return new JAXBElement<ConsultarCatalogoDesarrolloInType>(_ConsultarCatalogoDesarrolloIn_QNAME, ConsultarCatalogoDesarrolloInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCatalogoPagoInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ConsultarCatalogoPagoIn")
    public JAXBElement<ConsultarCatalogoPagoInType> createConsultarCatalogoPagoIn(ConsultarCatalogoPagoInType value) {
        return new JAXBElement<ConsultarCatalogoPagoInType>(_ConsultarCatalogoPagoIn_QNAME, ConsultarCatalogoPagoInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCatalogoLenguajeOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ConsultarCatalogoLenguajeOut")
    public JAXBElement<ConsultarCatalogoLenguajeOutType> createConsultarCatalogoLenguajeOut(ConsultarCatalogoLenguajeOutType value) {
        return new JAXBElement<ConsultarCatalogoLenguajeOutType>(_ConsultarCatalogoLenguajeOut_QNAME, ConsultarCatalogoLenguajeOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModificarCatalogoDesarrolloInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ModificarCatalogoDesarrolloIn")
    public JAXBElement<ModificarCatalogoDesarrolloInType> createModificarCatalogoDesarrolloIn(ModificarCatalogoDesarrolloInType value) {
        return new JAXBElement<ModificarCatalogoDesarrolloInType>(_ModificarCatalogoDesarrolloIn_QNAME, ModificarCatalogoDesarrolloInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrearCatalogoCuentaOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "CrearCatalogoCuentaOut")
    public JAXBElement<CrearCatalogoCuentaOutType> createCrearCatalogoCuentaOut(CrearCatalogoCuentaOutType value) {
        return new JAXBElement<CrearCatalogoCuentaOutType>(_CrearCatalogoCuentaOut_QNAME, CrearCatalogoCuentaOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrearCatalogoDesarrolloInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "CrearCatalogoDesarrolloIn")
    public JAXBElement<CrearCatalogoDesarrolloInType> createCrearCatalogoDesarrolloIn(CrearCatalogoDesarrolloInType value) {
        return new JAXBElement<CrearCatalogoDesarrolloInType>(_CrearCatalogoDesarrolloIn_QNAME, CrearCatalogoDesarrolloInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrearCatalogoLenguajeInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "CrearCatalogoLenguajeIn")
    public JAXBElement<CrearCatalogoLenguajeInType> createCrearCatalogoLenguajeIn(CrearCatalogoLenguajeInType value) {
        return new JAXBElement<CrearCatalogoLenguajeInType>(_CrearCatalogoLenguajeIn_QNAME, CrearCatalogoLenguajeInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrearCatalogoDesarrolloOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "CrearCatalogoDesarrolloOut")
    public JAXBElement<CrearCatalogoDesarrolloOutType> createCrearCatalogoDesarrolloOut(CrearCatalogoDesarrolloOutType value) {
        return new JAXBElement<CrearCatalogoDesarrolloOutType>(_CrearCatalogoDesarrolloOut_QNAME, CrearCatalogoDesarrolloOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCatalogoCategoriaOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ConsultarCatalogoCategoriaOut")
    public JAXBElement<ConsultarCatalogoCategoriaOutType> createConsultarCatalogoCategoriaOut(ConsultarCatalogoCategoriaOutType value) {
        return new JAXBElement<ConsultarCatalogoCategoriaOutType>(_ConsultarCatalogoCategoriaOut_QNAME, ConsultarCatalogoCategoriaOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCatalogoDesarrolloOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ConsultarCatalogoDesarrolloOut")
    public JAXBElement<ConsultarCatalogoDesarrolloOutType> createConsultarCatalogoDesarrolloOut(ConsultarCatalogoDesarrolloOutType value) {
        return new JAXBElement<ConsultarCatalogoDesarrolloOutType>(_ConsultarCatalogoDesarrolloOut_QNAME, ConsultarCatalogoDesarrolloOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCatalogoPagoOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ConsultarCatalogoPagoOut")
    public JAXBElement<ConsultarCatalogoPagoOutType> createConsultarCatalogoPagoOut(ConsultarCatalogoPagoOutType value) {
        return new JAXBElement<ConsultarCatalogoPagoOutType>(_ConsultarCatalogoPagoOut_QNAME, ConsultarCatalogoPagoOutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModificarCatalogoCategoriaInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ModificarCatalogoCategoriaIn")
    public JAXBElement<ModificarCatalogoCategoriaInType> createModificarCatalogoCategoriaIn(ModificarCatalogoCategoriaInType value) {
        return new JAXBElement<ModificarCatalogoCategoriaInType>(_ModificarCatalogoCategoriaIn_QNAME, ModificarCatalogoCategoriaInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModificarCatalogoMonedaOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.allshop.com/framework/core/ws/CatalogosCorporativos", name = "ModificarCatalogoMonedaOut")
    public JAXBElement<ModificarCatalogoMonedaOutType> createModificarCatalogoMonedaOut(ModificarCatalogoMonedaOutType value) {
        return new JAXBElement<ModificarCatalogoMonedaOutType>(_ModificarCatalogoMonedaOut_QNAME, ModificarCatalogoMonedaOutType.class, null, value);
    }

}
