//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.15 at 11:05:44 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.allshop.com/framework/core/ws/common/ElementosComunes", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.allshop.framework.core.ws.common.elementoscomunes;
